import type { NextPage } from 'next'
import Head from 'next/head'

const SignIn: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <div>
                    <form method={"post"} action={"/api/sign-in"}>
                        login:
                        <input type={"text"} name={"login"}/>
                        <hr/>
                        password:
                        <input type={"password"} name={"password"}/>
                        <hr/>
                        <button type={"submit"} title={"process"}>process</button>
                        <hr/>
                    </form>
                </div>
            </main>
        </div>
    )
}

export default SignIn
